---
title: "Fig 3 mouse fork"
output: html_notebook
---

Load Ruslan's data and scripts
```{r}
library(scde)
source("/d0/home/solrust/NC/functions-copy.r")
library(ggplot2)
library(cowplot)
```


```{r}
load('snapshot.RData')
load("cells.RData")
tr <- readRDS('z.ensemble11.rds')
```

ppt plot
```{r fig.height=6,fig.width=6}
t.plot.pptl(zm_glial,vi=vi,lwd=2,col=adjustcolor(1,alpha=I(0.08)))
```
```{r}
t.plot.ppt(zm_glial[[1]])
```

manual
```{r fig.height=4,fig.width=4}
#emb <- tp$Y; 
full.emb <- tp$Y; full.emb[,1] <- -1*full.emb[,1]
emb <- full.emb; emb <- emb[emb[,2]< -14,];
# factor
fac <- as.factor(setNames(clcol,rownames(tp$Y)))
fac <- setNames(rep('Migrating',nrow(emb)),rownames(emb)); 
fac[names(fac) %in% cell.symp] <- 'Autonomic'
fac[names(fac) %in% cell.mesench] <- 'Mesenchymal'
#fac[names(fac) %in% cell.sens] <- 'Sensory'
#fac[names(fac) %in% cell.symp] <- 'Autonomic'
# clean up corners
fac[emb[names(fac),1] < -5 & emb[names(fac),2]< -27] <- 'Mesenchymal'
fac[emb[names(fac),1] > 3 & emb[names(fac),2]< -20] <- 'Autonomic'
fac <- as.factor(fac)
# tree
r <- tr
F <- t(t(t(full.emb[r$cells,])%*%r$R)/colSums(r$R))
al <- get.edgelist(graph.adjacency(r$B>0))
al <- matrix(as.integer(al),ncol=2)
#segments(F[1,al[,1]],F[2,al[,1]],F[1,al[,2]],F[2,al[,2]],lwd=lwd,col=col)
tr.pos <- data.frame(x0=F[1,al[,1]],y0=F[2,al[,1]],x1=F[1,al[,2]],y1=F[2,al[,2]])
rm(F);
#geom_line(data=pt.pos[1:3.2e3,],aes(x,y),alpha=0.8,size=0.5) 
tr.pos <- tr.pos[tr.pos[,2] <= max(emb[,2]) & tr.pos[,1] >= min(emb[,1]),]
```


```{r fig.height=1,fig.width=1}
size <- 1; alpha=0.7;
mpal <- c('Autonomic'='blue3','Mesenchymal'='darkgreen','Migrating'='grey50')
mpal <- c('Autonomic'='#BA49F2FF','Mesenchymal'='#F28149FF','Migrating'='#F249BAFF')
theme <-  theme_bw() + ggplot2::theme(legend.background=ggplot2::element_rect(fill=ggplot2::alpha("white", 0.6)),plot.margin=ggplot2::margin())
p0 <- sccore:::styleEmbeddingPlot(sccore:::embeddingPlot(emb,groups=fac,mark.groups=F,plot.theme=theme,size=size,alpha=alpha,palette = mpal,raster=T,raster.width=1.5,raster.height=1.5))+
  #scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = expand_scale(add = c(0.5,0))) + 
  theme(panel.grid.major = element_blank()) +
  geom_segment(data=tr.pos,aes(x=x0,y=y0,xend=x1,yend=y1),alpha=0.8,size=0.5) 
p0
```

```{r}
gl <- rev(c("Phox2b","Prrx1",'Sox10'))
#gl <- rev(c("Phox2b","Prrx1"))
pl <- lapply(gl,function(g) 
  sccore:::styleEmbeddingPlot(sccore:::embeddingPlot(emb,colors=fpm[g,rownames(emb)],plot.theme=theme,size=size,alpha=alpha,raster=T,raster.width=1.5,raster.height=1.5))+
  #scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = expand_scale(add = c(0.5,0))) + 
  theme(panel.grid.major = element_blank()) +
  geom_segment(data=tr.pos,aes(x=x0,y=y0,xend=x1,yend=y1),alpha=0.8,size=0.5) +
  geom_label(x=Inf,y=-Inf,vjust=0,hjust=1,label=g,data=data.frame(x=c(1)),label.size=0)
)
```

```{r fig.width=1,fig.height=1*0.94*4}
pp <- plot_grid(plotlist=c(list(p0),pl),ncol=1)
pp
```
```{r}
pdf(file='nc.fork.genes2.pdf',width=1,height=1*0.94*4); print(pp); dev.off();
```

```{r fig.width=4,fig.height=4}

sccore:::embeddingPlot(tp$Y,colors=pagoda2:::val2col(fpm['Phox2b',rownames(tp$Y)]),plot.theme=theme_bw()) %>% sccore:::styleEmbeddingPlot()
```

